AZURE_HOME=/home/azure
JAVA_HOME=$AZURE_HOME/Java/jdk1.7.0_06
CLASSPATH=$JAVA_HOME/lib
ANDROID_HOME=$AZURE_HOME/android/android-sdks
ANDROID_NDK_HOME=$AZURE_HOME/android/android-ndk

PATH=$PATH:$HOME/.local/bin:$HOME/bin:$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME:$ANDROID_HOME/tools

export PATH JAVA_HOME CLASSPATH ANDROID_HOME ANDROID_NDK_HOME
